version: '3.8'

services:
  app:
    container_name: ${APP_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./build/dockerfiles/app/Dockerfile
    volumes: 
      - ./app:/usr/local/go/src/mcd_nut_app/app
      - .env:/usr/local/go/src/mcd_nut_app/app/.env
    tty: true 
    depends_on:
      - db
    ports:
      - ${APP_PORT}:3000

  db:
    container_name: ${DB_HOST}
    build:
      context: .
      dockerfile: ./build/dockerfiles/postgresql/Dockerfile
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./app/database/init:/docker-entrypoint-initdb.d 
    ports:
      - ${DB_PORT}:5433

volumes:
  db-store:
